[package]
name = "circuit_reader"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bincode = "1.3.3"
secq256k1 = { path = "../secq256k1" }
spartan = { path = "../Spartan-secq" }
ff = "0.12.0"
byteorder = "1.4.3"
group = "0.12.0"
itertools = "0.9.0"

[[bin]]
name = "gen_spartan_inst"
path = "src/bin/gen_spartan_inst.rs"



